@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed May 10 16:19:26 +0200 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim gt_func_synth -key {Post-Synthesis:others:Functional:gt} -tclbatch gt.tcl -view C:/Users/simon/OneDrive - Politecnico di Milano/3/Reti Logiche/project_reti_logiche/tb3_all_outs_func_synth.wcfg -log simulate.log"
call xsim  gt_func_synth -key {Post-Synthesis:others:Functional:gt} -tclbatch gt.tcl -view C:/Users/simon/OneDrive - Politecnico di Milano/3/Reti Logiche/project_reti_logiche/tb3_all_outs_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
